package consts

const (
	/*
		common field names
	*/
	FieldAPIHostname                = "api_hostname"
	FieldAPIToken                   = "api_token"
	FieldAWS                        = "aws"
	FieldAWSAccessKeyID             = "aws_access_key_id"
	FieldAWSIAMEndpoint             = "aws_iam_endpoint"
	FieldAWSProfile                 = "aws_profile"
	FieldAWSRegion                  = "aws_region"
	FieldAWSRoleARN                 = "aws_role_arn"
	FieldAWSRoleSessionName         = "aws_role_session_name"
	FieldAWSSTSEndpoint             = "aws_sts_endpoint"
	FieldAWSSecretAccessKey         = "aws_secret_access_key"
	FieldAWSSessionToken            = "aws_session_token"
	FieldAWSSharedCredentialsFile   = "aws_shared_credentials_file"
	FieldAWSWebIdentityTokenFile    = "aws_web_identity_token_file"
	FieldAccessKey                  = "access_key"
	FieldAddress                    = "address"
	FieldAdminURL                   = "admin_url"
	FieldAlgorithm                  = "algorithm"
	FieldAllowGenerateKey           = "allow_generate_key"
	FieldAllowReplaceKey            = "allow_replace_key"
	FieldAllowStoreKey              = "allow_store_key"
	FieldAnyMount                   = "any_mount"
	FieldAuditNonHMACRequestKeys    = "audit_non_hmac_request_keys"
	FieldAuditNonHMACResponseKeys   = "audit_non_hmac_response_keys"
	FieldAuthLoginAWS               = "auth_login_aws"
	FieldAuthLoginAzure             = "auth_login_azure"
	FieldAuthLoginCert              = "auth_login_cert"
	FieldAuthLoginDefault           = "auth_login"
	FieldAuthLoginGCP               = "auth_login_gcp"
	FieldAuthLoginJWT               = "auth_login_jwt"
	FieldAuthLoginKerberos          = "auth_login_kerberos"
	FieldAuthLoginOCI               = "auth_login_oci"
	FieldAuthLoginOIDC              = "auth_login_oidc"
	FieldAuthLoginRadius            = "auth_login_radius"
	FieldAuthLoginUserpass          = "auth_login_userpass"
	FieldAuthMethodAccessors        = "auth_method_accessors"
	FieldAuthMethodTypes            = "auth_method_types"
	FieldAuthType                   = "auth_type"
	FieldAuthenticatorURL           = "authenticator_url"
	FieldAuthorization              = "authorization"
	FieldAzure                      = "azure"
	FieldBackend                    = "backend"
	FieldBaseURL                    = "base_url"
	FieldCACertDir                  = "ca_cert_dir"
	FieldCACertFile                 = "ca_cert_file"
	FieldCallbackAddress            = "callback_address"
	FieldCallbackListenerAddress    = "callback_listener_address"
	FieldCertFile                   = "cert_file"
	FieldClientAuth                 = "client_auth"
	FieldClientEmail                = "client_email"
	FieldClientID                   = "client_id"
	FieldClientSecret               = "client_secret"
	FieldClientToken                = "client_token"
	FieldCredentials                = "credentials"
	FieldCurve                      = "curve"
	FieldData                       = "data"
	FieldDataJSON                   = "data_json"
	FieldDefaultLeaseTTL            = "default_lease_ttl_seconds"
	FieldDepth                      = "depth"
	FieldDescription                = "description"
	FieldDigits                     = "digits"
	FieldDisableFastNegotiation     = "disable_fast_negotiation"
	FieldDisableRemount             = "disable_remount"
	FieldDisplayName                = "display_name"
	FieldEndpoint                   = "endpoint"
	FieldEnvironment                = "environment"
	FieldExclusive                  = "exclusive"
	FieldExplicitMaxTTL             = "explicit_max_ttl"
	FieldExternal                   = "external"
	FieldExternalEntropyAccess      = "external_entropy_access"
	FieldFailureTolerance           = "failure_tolerance"
	FieldForceRWSession             = "force_rw_session"
	FieldGroupID                    = "group_id"
	FieldGroupName                  = "group_name"
	FieldHeaderValue                = "header_value"
	FieldHealthy                    = "healthy"
	FieldIAMHttpRequestMethod       = "iam_http_request_method"
	FieldIAMRequestBody             = "iam_request_body"
	FieldIAMRequestHeaders          = "iam_request_headers"
	FieldIAMRequestURL              = "iam_request_url"
	FieldID                         = "id"
	FieldIdentityEntityIDs          = "identity_entity_ids"
	FieldIdentityGroupIDs           = "identity_group_ids"
	FieldIdpURL                     = "idp_url"
	FieldIntegrationKey             = "integration_key"
	FieldInternal                   = "internal"
	FieldIssuer                     = "issuer"
	FieldJWT                        = "jwt"
	FieldKMSKey                     = "kms_key"
	FieldKRB5ConfPath               = "krb5conf_path"
	FieldKeyBits                    = "key_bits"
	FieldKeyFile                    = "key_file"
	FieldKeyID                      = "key_id"
	FieldKeyLabel                   = "key_label"
	FieldKeyName                    = "key_name"
	FieldKeySize                    = "key_size"
	FieldKeyType                    = "key_type"
	FieldKeytabPath                 = "keytab_path"
	FieldLeader                     = "leader"
	FieldLeaseDuration              = "lease_duration"
	FieldLeaseID                    = "lease_id"
	FieldLeaseRenewable             = "lease_renewable"
	FieldLeaseStarted               = "lease_started"
	FieldLibrary                    = "library"
	FieldLocal                      = "local"
	FieldMFAMethodIDs               = "mfa_method_ids"
	FieldMaxLeaseTTL                = "max_lease_ttl_seconds"
	FieldMaxValidationAttempts      = "max_validation_attempts"
	FieldMechanism                  = "mechanism"
	FieldMemberEntityIDs            = "member_entity_ids"
	FieldMemberGroupIDs             = "member_group_ids"
	FieldMetadata                   = "metadata"
	FieldMethod                     = "method"
	FieldMethodID                   = "method_id"
	FieldMount                      = "mount"
	FieldMountAccessor              = "mount_accessor"
	FieldName                       = "name"
	FieldNames                      = "names"
	FieldNamespace                  = "namespace"
	FieldNamespaceID                = "namespace_id"
	FieldNamespacePath              = "namespace_path"
	FieldNoDefaultPolicy            = "no_default_policy"
	FieldNoParent                   = "no_parent"
	FieldNumUses                    = "num_uses"
	FieldOptimisticFailureTolerance = "optimistic_failure_tolerance"
	FieldOrgAlias                   = "org_alias"
	FieldOrgName                    = "org_name"
	FieldOrphan                     = "orphan"
	FieldPKCS                       = "pkcs"
	FieldParameters                 = "parameters"
	FieldPassword                   = "password"
	FieldPasswordFile               = "password_file"
	FieldPath                       = "path"
	FieldPathFQ                     = "path_fq"
	FieldPeriod                     = "period"
	FieldPin                        = "pin"
	FieldPolicies                   = "policies"
	FieldPrimaryEmail               = "primary_email"
	FieldPushInfo                   = "push_info"
	FieldQRSize                     = "qr_size"
	FieldRealm                      = "realm"
	FieldRedundancyZones            = "redundancy_zones"
	FieldRedundancyZonesJSON        = "redundancy_zones_json"
	FieldRegion                     = "region"
	FieldRemoveInstanceName         = "remove_instance_name"
	FieldRenewIncrement             = "renew_increment"
	FieldRenewMinLease              = "renew_min_lease"
	FieldRenewable                  = "renewable"
	FieldRequestHeaders             = "request_headers"
	FieldResource                   = "resource"
	FieldResourceGroupName          = "resource_group_name"
	FieldRole                       = "role"
	FieldRoleName                   = "role_name"
	FieldScope                      = "scope"
	FieldSealWrap                   = "seal_wrap"
	FieldSecretKey                  = "secret_key"
	FieldServers                    = "servers"
	FieldServersJSON                = "servers_json"
	FieldService                    = "service"
	FieldServiceAccount             = "service_account"
	FieldSettingsFileBase64         = "settings_file_base64"
	FieldSkew                       = "skew"
	FieldSkipGetVaultVersion        = "skip_get_vault_version"
	FieldSkipTLSVerify              = "skip_tls_verify"
	FieldSlot                       = "slot"
	FieldSubscriptionID             = "subscription_id"
	FieldTLSServerName              = "tls_server_name"
	FieldTTL                        = "ttl"
	FieldTenantID                   = "tenant_id"
	FieldToken                      = "token"
	FieldTokenLabel                 = "token_label"
	FieldType                       = "type"
	FieldUUID                       = "uuid"
	FieldUpgradeInfo                = "upgrade_info"
	FieldUpgradeInfoJSON            = "upgrade_info_json"
	FieldUsePasscode                = "use_passcode"
	FieldUseSignature               = "use_signature"
	FieldUsername                   = "username"
	FieldUsernameFormat             = "username_format"
	FieldVMName                     = "vm_name"
	FieldVMSSName                   = "vmss_name"
	FieldVaultName                  = "vault_name"
	FieldVaultVersionOverride       = "vault_version_override"
	FieldVersion                    = "version"
	FieldVoters                     = "voters"
	FieldWrappedToken               = "wrapped_token"
	FieldWrappingAccessor           = "wrapping_accessor"
	FieldWrappingTTL                = "wrapping_ttl"

	/*
		common environment variables
	*/
	EnvVarVaultNamespaceImport = "TERRAFORM_VAULT_NAMESPACE_IMPORT"
	EnvVarSkipChildToken       = "TERRAFORM_VAULT_SKIP_CHILD_TOKEN"
	// EnvVarUsername to get the username for the userpass auth method
	EnvVarUsername = "TERRAFORM_VAULT_USERNAME"
	// EnvVarPassword to get the password for the userpass auth method
	EnvVarPassword = "TERRAFORM_VAULT_PASSWORD"
	// EnvVarPasswordFile to get the password for the userpass auth method
	EnvVarPasswordFile = "TERRAFORM_VAULT_PASSWORD_FILE"
	// EnvVarGCPAuthJWT to get the signed JWT for the gcp auth method
	EnvVarGCPAuthJWT = "TERRAFORM_VAULT_GCP_AUTH_JWT"
	// EnvVarVaultAuthJWT to login via the Vault jwt engine.
	EnvVarVaultAuthJWT = "TERRAFORM_VAULT_AUTH_JWT"
	// EnvVarAzureAuthJWT to login into Vault's azure auth engine.
	EnvVarAzureAuthJWT = "TERRAFORM_VAULT_AZURE_AUTH_JWT"

	EnvVarGoogleApplicationCreds = "GOOGLE_APPLICATION_CREDENTIALS"

	// EnvVarKrbSPNEGOToken to get the signed JWT for the gcp auth method
	EnvVarKrbSPNEGOToken = "KRB_SPNEGO_TOKEN"
	// EnvVarKRB5Conf path to the krb5.conf file.
	EnvVarKRB5Conf = "KRB5_CONFIG"
	// EnvVarKRBKeytab path the keytab file.
	EnvVarKRBKeytab = "KRB_KEYTAB"

	// EnvVarRadiusUsername for the Radius auth login
	EnvVarRadiusUsername = "RADIUS_USERNAME"
	// EnvVarRadiusPassword for the Radius auth login
	EnvVarRadiusPassword = "RADIUS_PASSWORD"

	/*
		common mount types
	*/
	MountTypeDatabase   = "database"
	MountTypePKI        = "pki"
	MountTypeAWS        = "aws"
	MountTypeKMIP       = "kmip"
	MountTypeRabbitMQ   = "rabbitmq"
	MountTypeNomad      = "nomad"
	MountTypeKubernetes = "kubernetes"
	MountTypeUserpass   = "userpass"
	MountTypeCert       = "cert"
	MountTypeGCP        = "gcp"
	MountTypeKerberos   = "kerberos"
	MountTypeRadius     = "radius"
	MountTypeOCI        = "oci"
	MountTypeOIDC       = "oidc"
	MountTypeJWT        = "jwt"
	MountTypeAzure      = "azure"
	MountTypeGitHub     = "github"
	MountTypeAD         = "ad"
	MountTypeConsul     = "consul"
	MountTypeTerraform  = "terraform"

	/*
		Vault version constants
	*/
	VaultVersion190 = "1.9.0"
	VaultVersion110 = "1.10.0"
	VaultVersion111 = "1.11.0"
	VaultVersion112 = "1.12.0"

	/*
		Vault auth methods
	*/
	AuthMethodAWS      = "aws"
	AuthMethodUserpass = "userpass"
	AuthMethodCert     = "cert"
	AuthMethodGCP      = "gcp"
	AuthMethodKerberos = "kerberos"
	AuthMethodRadius   = "radius"
	AuthMethodOCI      = "oci"
	AuthMethodOIDC     = "oidc"
	AuthMethodJWT      = "jwt"
	AuthMethodAzure    = "azure"

	/*
		misc. path related constants
	*/
	PathDelim      = "/"
	VaultAPIV1Root = "/v1"
)
