package spiffe

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/go-viper/mapstructure/v2"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-provider-vault/helper"
	"github.com/hashicorp/terraform-provider-vault/internal/consts"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/base"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/client"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/errutil"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/model"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/validators"
	"github.com/hashicorp/vault/api"
)

var roleNameRegexp = regexp.MustCompile("^(.+)/role/(.+)$")

// Ensure the implementation satisfies the resource.ResourceWithImportState interface
var _ resource.ResourceWithImportState = &SpiffeSecretBackendRoleResource{}

// NewSpiffeSecretBackendRoleResource returns the implementation for this resource to be
// imported by the Terraform Plugin Framework provider
func NewSpiffeSecretBackendRoleResource() resource.Resource {
	return &SpiffeSecretBackendRoleResource{}
}

// SpiffeSecretBackendRoleResource implements the methods that define this resource
type SpiffeSecretBackendRoleResource struct {
	base.ResourceWithConfigure
}

type SpiffeSecretBackendRoleModel struct {
	base.BaseModel

	Mount       types.String `tfsdk:"mount"`
	Name        types.String `tfsdk:"name"`
	Ttl         types.String `tfsdk:"ttl"`
	Template    types.String `tfsdk:"template"`
	UseJtiClaim types.Bool   `tfsdk:"use_jti_claim"`
}

type SpiffeSecretBackendRoleAPIModel struct {
	Name        string `json:"name" mapstructure:"name"`
	Ttl         string `json:"ttl" mapstructure:"ttl,omitempty"`
	Template    string `json:"template" mapstructure:"template"`
	UseJtiClaim bool   `json:"use_jti_claim" mapstructure:"use_jti_claim,omitempty"`
}

func (s *SpiffeSecretBackendRoleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_spiffe_secret_backend_role"
}

func (s *SpiffeSecretBackendRoleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			consts.FieldMount: schema.StringAttribute{
				Description: "Mount path for the SPIFFE secrets engine in Vault.",
				Required:    true,
			},
			consts.FieldName: schema.StringAttribute{
				Description: "Name of the SPIFFE role.",
				Required:    true,
			},
			consts.FieldTTL: schema.StringAttribute{
				Description: "TTL of the tokens generated by this role",
				Optional:    true,
				Computed:    true,
				Validators: []validator.String{
					validators.DurationValidator(),
				},
			},
			"template": schema.StringAttribute{
				Description: "The template string to use for generating tokens. This may be in stringified JSON or base64 format.",
				Required:    true,
			},
			"use_jti_claim": schema.BoolAttribute{
				Description: "If true, the jti (JWT ID) claim will be included in tokens generated from this role",
				Optional:    true,
				Computed:    true,
			},
		},
	}

	base.MustAddBaseSchema(&resp.Schema)
}

func (s *SpiffeSecretBackendRoleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SpiffeSecretBackendRoleModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	vaultClient, err := client.GetClient(ctx, s.Meta(), data.Namespace.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(errutil.ClientConfigureErr(err))
		return
	}

	vaultRequest, diagErr := s.getApiModel(ctx, &data)
	if diagErr.HasError() {
		resp.Diagnostics.Append(diagErr...)
		return
	}

	mountPath, err := s.path(&data)
	if err != nil {
		resp.Diagnostics.AddError("Error determining role path", err.Error())
		return
	}

	vaultResp, err := vaultClient.Logical().WriteWithContext(ctx, mountPath, vaultRequest)
	if err != nil {
		resp.Diagnostics.AddError(errutil.VaultCreateErr(err))
		return
	}

	if vaultResp == nil {
		resp.Diagnostics.AddError(errutil.VaultReadResponseNil())
		return
	}

	if diagErr := s.populateDataModelFromApi(ctx, &data, vaultResp); diagErr.HasError() {
		resp.Diagnostics.Append(diagErr...)
		return
	}

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (s *SpiffeSecretBackendRoleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SpiffeSecretBackendRoleModel
	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	vaultClient, err := client.GetClient(ctx, s.Meta(), data.Namespace.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(errutil.ClientConfigureErr(err))
		return
	}

	mountPath, err := s.path(&data)
	if err != nil {
		resp.Diagnostics.AddError("Error determining role path", err.Error())
		return
	}

	vaultResp, err := vaultClient.Logical().ReadWithContext(ctx, mountPath)
	if err != nil {
		resp.Diagnostics.AddError(errutil.VaultReadErr(err))
		return
	}
	if vaultResp == nil {
		resp.Diagnostics.AddError(errutil.VaultReadResponseNil())
		return
	}

	if diagErr := s.populateDataModelFromApi(ctx, &data, vaultResp); diagErr.HasError() {
		resp.Diagnostics.Append(diagErr...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (s *SpiffeSecretBackendRoleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data SpiffeSecretBackendRoleModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	vaultClient, err := client.GetClient(ctx, s.Meta(), data.Namespace.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(errutil.ClientConfigureErr(err))
		return
	}

	vaultRequest, diagErr := s.getApiModel(ctx, &data)
	if diagErr.HasError() {
		resp.Diagnostics.Append(diagErr...)
		return
	}

	mountPath, err := s.path(&data)
	if err != nil {
		resp.Diagnostics.AddError("Error determining role path", err.Error())
		return
	}

	vaultResp, err := vaultClient.Logical().WriteWithContext(ctx, mountPath, vaultRequest)
	if err != nil {
		resp.Diagnostics.AddError(errutil.VaultCreateErr(err))
		return
	}

	if vaultResp == nil {
		resp.Diagnostics.AddError(errutil.VaultReadResponseNil())
		return
	}

	if diagErr := s.populateDataModelFromApi(ctx, &data, vaultResp); diagErr.HasError() {
		resp.Diagnostics.Append(diagErr...)
		return
	}

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (s *SpiffeSecretBackendRoleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data SpiffeSecretBackendRoleModel

	// Read Terraform state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	vaultClient, err := client.GetClient(ctx, s.Meta(), data.Namespace.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(errutil.ClientConfigureErr(err))
		return
	}

	mountPath, err := s.path(&data)
	if err != nil {
		resp.Diagnostics.AddError("Error determining role path", err.Error())
		return
	}

	if _, err = vaultClient.Logical().Delete(mountPath); err != nil {
		resp.Diagnostics.AddError("Error deleting role", err.Error())
	}
}

func (s *SpiffeSecretBackendRoleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	mount, roleName, err := s.extractSpiffeRoleIdentifiers(req.ID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error parsing import identifier",
			fmt.Sprintf("The import identifier '%s' is not valid: %s", req.ID, err.Error()),
		)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(consts.FieldMount), mount)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(consts.FieldName), roleName)...)

	ns := os.Getenv(consts.EnvVarVaultNamespaceImport)
	if ns != "" {
		tflog.Info(
			ctx,
			fmt.Sprintf("Environment variable %s set, attempting TF state import", consts.EnvVarVaultNamespaceImport),
			map[string]any{consts.FieldNamespace: ns},
		)
		resp.Diagnostics.Append(
			resp.State.SetAttribute(ctx, path.Root(consts.FieldNamespace), ns)...,
		)
	}
}

func (s *SpiffeSecretBackendRoleResource) path(data *SpiffeSecretBackendRoleModel) (string, error) {
	mount := data.Mount.ValueString()
	name := data.Name.ValueString()
	if mount == "" || name == "" {
		return "", fmt.Errorf("mount and name are required fields got mount: %q name: %q", mount, name)
	}
	return fmt.Sprintf("%s/role/%s", mount, name), nil
}

func (s *SpiffeSecretBackendRoleResource) getApiModel(ctx context.Context, data *SpiffeSecretBackendRoleModel) (map[string]any, diag.Diagnostics) {
	apiModel := SpiffeSecretBackendRoleAPIModel{
		Name:        data.Name.ValueString(),
		Ttl:         data.Ttl.ValueString(),
		Template:    data.Template.ValueString(),
		UseJtiClaim: data.UseJtiClaim.ValueBool(),
	}

	var vaultRequest map[string]any
	if err := mapstructure.Decode(apiModel, &vaultRequest); err != nil {
		return nil, diag.Diagnostics{
			diag.NewErrorDiagnostic("Failed to decode SPIFFE role API model to map", err.Error()),
		}
	}

	return vaultRequest, nil
}

func (s *SpiffeSecretBackendRoleResource) populateDataModelFromApi(_ context.Context, data *SpiffeSecretBackendRoleModel, resp *api.Secret) diag.Diagnostics {
	if resp == nil || resp.Data == nil {
		return diag.Diagnostics{
			diag.NewErrorDiagnostic("Missing data in API response", "The API response or response data was nil."),
		}
	}

	var readResp SpiffeSecretBackendRoleAPIModel
	if err := model.ToAPIModel(resp.Data, &readResp); err != nil {
		return diag.Diagnostics{
			diag.NewErrorDiagnostic("Unable to translate Vault response data", err.Error()),
		}
	}
	data.Name = types.StringValue(readResp.Name)
	data.Ttl = types.StringValue(helper.FlattenVaultDuration(json.Number(readResp.Ttl)))
	data.Template = types.StringValue(readResp.Template)
	data.UseJtiClaim = types.BoolValue(readResp.UseJtiClaim)

	return diag.Diagnostics{}
}

func (s *SpiffeSecretBackendRoleResource) extractSpiffeRoleIdentifiers(id string) (string, string, error) {
	if id == "" {
		return "", "", fmt.Errorf("import identifier cannot be empty")
	}
	// Trim leading slash if present
	id = strings.Trim(id, "/")

	if !roleNameRegexp.MatchString(id) {
		return "", "", fmt.Errorf("import identifier must be of the form '<mount>/role/<rolename>', "+
			"namespace can be specified using the env var %s", consts.EnvVarVaultNamespaceImport)
	}

	matches := roleNameRegexp.FindStringSubmatch(id)
	if len(matches) != 3 {
		return "", "", fmt.Errorf("import identifier must be of the form '<mount>/role/<rolename>', "+
			"namespace can be specified using the env var %s", consts.EnvVarVaultNamespaceImport)
	}

	mount := strings.TrimSpace(matches[1])
	if mount == "" {
		return "", "", fmt.Errorf("mount cannot be empty")
	}

	roleName := strings.TrimSpace(matches[2])
	if roleName == "" {
		return "", "", fmt.Errorf("role name cannot be empty")
	}

	return mount, roleName, nil
}
