// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package vault

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/hashicorp/terraform-provider-vault/internal/consts"
	"github.com/hashicorp/terraform-provider-vault/internal/provider"
	syncutil "github.com/hashicorp/terraform-provider-vault/internal/sync"
)

const (
	fieldAccessToken     = "access_token"
	fieldRepositoryOwner = "repository_owner"
	fieldRepositoryName  = "repository_name"
	ghSyncType           = "gh"
)

var githubSyncWriteFields = []string{
	fieldAccessToken,
	fieldRepositoryOwner,
	fieldRepositoryName,
	consts.FieldSecretNameTemplate,
	consts.FieldGranularity,
	consts.FieldAppName,
	consts.FieldInstallationID,
}

var githubSyncUpdateFields = []string{
	fieldAccessToken,
	consts.FieldSecretNameTemplate,
	consts.FieldAppName,
	consts.FieldInstallationID,
}

var githubSyncReadFields = []string{
	fieldRepositoryOwner,
	fieldRepositoryName,
	consts.FieldGranularity,
	consts.FieldSecretNameTemplate,
	consts.FieldAppName,
	consts.FieldInstallationID,
}

// These fields are conditionally added to read and write operations when Vault 1.18+ is detected
var githubSyncFieldsV118 = []string{
	consts.FieldSecretsLocation,
	consts.FieldEnvironmentName,
}

// These fields are conditionally added to read and write operations when Vault 1.19+ is detected
var githubSyncFieldsV119 = []string{
	consts.FieldAllowedIPv4Addresses,
	consts.FieldAllowedIPv6Addresses,
	consts.FieldAllowedPorts,
	consts.FieldDisableStrictNetworking,
}

func githubSecretsSyncDestinationResource() *schema.Resource {
	return provider.MustAddSecretsSyncCommonSchema(&schema.Resource{
		CreateContext: provider.MountCreateContextWrapper(githubSecretsSyncDestinationCreateUpdate, provider.VaultVersion116),
		ReadContext:   provider.ReadContextWrapper(githubSecretsSyncDestinationRead),
		UpdateContext: githubSecretsSyncDestinationCreateUpdate,
		DeleteContext: githubSecretsSyncDestinationDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			consts.FieldName: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Unique name of the github destination.",
				ForceNew:    true,
			},
			fieldAccessToken: {
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				Description: "Fine-grained or personal access token.",
			},
			fieldRepositoryOwner: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "GitHub organization or username that owns the repository.",
				ForceNew:    true,
			},
			fieldRepositoryName: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Name of the repository.",
				ForceNew:    true,
			},
			consts.FieldAppName: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The user-defined name of the GitHub App configuration.",
			},
			consts.FieldInstallationID: {
				Type:     schema.TypeInt,
				Optional: true,
				Description: "The ID of the installation generated by GitHub when the app referenced by the " +
					"app_name was installed in the user's GitHub account. Necessary if the app_name field is also provided.",
			},
			consts.FieldAllowedIPv4Addresses: {
				Type:     schema.TypeList,
				Optional: true,
				Description: "List of allowed IPv4 addresses in CIDR notation (e.g., 192.168.1.1/32) " +
					"for outbound connections from Vault to the destination. If not set, all IPv4 addresses are allowed.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			consts.FieldAllowedIPv6Addresses: {
				Type:     schema.TypeList,
				Optional: true,
				Description: "List of allowed IPv6 addresses in CIDR notation (e.g., 2001:db8::1/128) " +
					"for outbound connections from Vault to the destination. If not set, all IPv6 addresses are allowed.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			consts.FieldAllowedPorts: {
				Type:     schema.TypeList,
				Optional: true,
				Description: "List of allowed ports for outbound connections from Vault to the destination. " +
					"If not set, all ports are allowed.",
				Elem: &schema.Schema{
					Type: schema.TypeInt,
				},
			},
			consts.FieldDisableStrictNetworking: {
				Type:     schema.TypeBool,
				Optional: true,
				Description: "If set to true, disables strict networking enforcement for this destination. " +
					"When disabled, Vault will not enforce allowed IP addresses and ports.",
			},
			consts.FieldSecretsLocation: {
				Type:     schema.TypeString,
				Optional: true,
				Description: "Determines where secrets will be stored in GitHub." +
					"Valid values are 'repository' or 'environment'.",
			},
			consts.FieldEnvironmentName: {
				Type:     schema.TypeString,
				Optional: true,
				Description: "GitHub environment name where secrets will be synced." +
					"Required when secrets_location is set to 'environment'.",
				ForceNew: true,
			},
		},
	})
}

func githubSecretsSyncDestinationCreateUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	writeFields := make([]string, len(githubSyncWriteFields))
	copy(writeFields, githubSyncWriteFields)
	readFields := make([]string, len(githubSyncReadFields))
	copy(readFields, githubSyncReadFields)

	// Add Vault 1.18+ fields if supported
	isV118Supported := provider.IsAPISupported(meta, provider.VaultVersion118)
	if isV118Supported {
		writeFields = append(writeFields, githubSyncFieldsV118...)
		readFields = append(readFields, githubSyncFieldsV118...)
	}

	// Add Vault 1.19+ fields if supported
	isV119Supported := provider.IsAPISupported(meta, provider.VaultVersion119)
	if isV119Supported {
		writeFields = append(writeFields, githubSyncFieldsV119...)
		readFields = append(readFields, githubSyncFieldsV119...)
	}

	return syncutil.SyncDestinationCreateUpdate(ctx, d, meta, ghSyncType, writeFields, readFields)
}

func githubSecretsSyncDestinationRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	readFields := make([]string, len(githubSyncReadFields))
	copy(readFields, githubSyncReadFields)

	// Add Vault 1.18+ fields if supported
	isV118Supported := provider.IsAPISupported(meta, provider.VaultVersion118)
	if isV118Supported {
		readFields = append(readFields, githubSyncFieldsV118...)
	}

	// Add Vault 1.19+ fields if supported
	isV119Supported := provider.IsAPISupported(meta, provider.VaultVersion119)
	if isV119Supported {
		readFields = append(readFields, githubSyncFieldsV119...)
	}

	return syncutil.SyncDestinationRead(ctx, d, meta, ghSyncType, readFields, map[string]string{
		consts.FieldGranularity: consts.FieldGranularityLevel,
	})
}

func githubSecretsSyncDestinationDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return syncutil.SyncDestinationDelete(ctx, d, meta, ghSyncType)
}
