// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package vault

import (
	"context"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/hashicorp/terraform-provider-vault/internal/consts"
	"github.com/hashicorp/terraform-provider-vault/internal/provider"
	syncutil "github.com/hashicorp/terraform-provider-vault/internal/sync"
)

const (
	fieldAccessToken     = "access_token"
	fieldRepositoryOwner = "repository_owner"
	fieldRepositoryName  = "repository_name"
	ghSyncType           = "gh"
)

func githubSecretsSyncDestinationResource() *schema.Resource {
	return provider.MustAddSecretsSyncCommonSchema(&schema.Resource{
		CreateContext: provider.MountCreateContextWrapper(githubSecretsSyncDestinationCreateUpdate, provider.VaultVersion116),
		ReadContext:   provider.ReadContextWrapper(githubSecretsSyncDestinationRead),
		UpdateContext: githubSecretsSyncDestinationCreateUpdate,
		DeleteContext: githubSecretsSyncDestinationDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			consts.FieldName: {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Unique name of the github destination.",
				ForceNew:    true,
			},
			fieldAccessToken: {
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				Description: "Fine-grained or personal access token.",
			},
			fieldRepositoryOwner: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "GitHub organization or username that owns the repository.",
				ForceNew:    true,
			},
			fieldRepositoryName: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Name of the repository.",
				ForceNew:    true,
			},
			consts.FieldAppName: {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The user-defined name of the GitHub App configuration.",
			},
			consts.FieldInstallationID: {
				Type:     schema.TypeInt,
				Optional: true,
				Description: "The ID of the installation generated by GitHub when the app referenced by the " +
					"app_name was installed in the user's GitHub account. Necessary if the app_name field is also provided.",
			},
			consts.FieldAllowedIPv4Addresses: {
				Type:     schema.TypeSet,
				Optional: true,
				Description: "List of allowed IPv4 addresses in CIDR notation (e.g., 192.168.1.1/32) " +
					"for outbound connections from Vault to the destination. If not set, all IPv4 addresses are allowed.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			consts.FieldAllowedIPv6Addresses: {
				Type:     schema.TypeSet,
				Optional: true,
				Description: "List of allowed IPv6 addresses in CIDR notation (e.g., 2001:db8::1/128) " +
					"for outbound connections from Vault to the destination. If not set, all IPv6 addresses are allowed.",
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			consts.FieldAllowedPorts: {
				Type:     schema.TypeSet,
				Optional: true,
				Description: "List of allowed ports for outbound connections from Vault to the destination. " +
					"If not set, all ports are allowed.",
				Elem: &schema.Schema{
					Type: schema.TypeInt,
				},
			},
			consts.FieldDisableStrictNetworking: {
				Type:     schema.TypeBool,
				Optional: true,
				Description: "If set to true, disables strict networking enforcement for this destination. " +
					"When disabled, Vault will not enforce allowed IP addresses and ports.",
			},
			consts.FieldSecretsLocation: {
				Type:     schema.TypeString,
				Optional: true,
				Description: "Determines where secrets will be stored in GitHub. " +
					"Valid values are 'repository' or 'environment'.",
			},
			consts.FieldEnvironmentName: {
				Type:     schema.TypeString,
				Optional: true,
				Description: "GitHub environment name where secrets will be synced. " +
					"Required when secrets_location is set to 'environment'.",
				ForceNew: true,
			},
		},
	})
}

func githubSecretsSyncDestinationCreateUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client, e := provider.GetClient(d, meta)
	if e != nil {
		return diag.FromErr(e)
	}

	name := d.Get(consts.FieldName).(string)
	path := syncutil.SecretsSyncDestinationPath(name, ghSyncType)

	writeFields := []string{
		fieldAccessToken,
		fieldRepositoryOwner,
		fieldRepositoryName,
		consts.FieldSecretNameTemplate,
		consts.FieldGranularity,
		consts.FieldAppName,
		consts.FieldInstallationID,
	}
	readFields := []string{
		fieldRepositoryOwner,
		fieldRepositoryName,
		consts.FieldGranularity,
		consts.FieldSecretNameTemplate,
		consts.FieldAppName,
		consts.FieldInstallationID,
	}

	// Add Vault 1.18+ fields if supported
	isV118Supported := provider.IsAPISupported(meta, provider.VaultVersion118)
	if isV118Supported {
		writeFields = append(writeFields,
			consts.FieldSecretsLocation,
			consts.FieldEnvironmentName,
		)
		readFields = append(readFields,
			consts.FieldSecretsLocation,
			consts.FieldEnvironmentName,
		)
	}

	// Add Vault 1.19+ fields if supported
	isV119Supported := provider.IsAPISupported(meta, provider.VaultVersion119)
	if isV119Supported {
		writeFields = append(writeFields,
			consts.FieldAllowedIPv4Addresses,
			consts.FieldAllowedIPv6Addresses,
			consts.FieldAllowedPorts,
			consts.FieldDisableStrictNetworking,
		)
		readFields = append(readFields,
			consts.FieldAllowedIPv4Addresses,
			consts.FieldAllowedIPv6Addresses,
			consts.FieldAllowedPorts,
			consts.FieldDisableStrictNetworking,
		)
	}

	data := map[string]interface{}{}

	for _, k := range writeFields {
		if v, ok := d.GetOk(k); ok {
			// Convert TypeSet to list for JSON serialization
			if k == consts.FieldAllowedIPv4Addresses || k == consts.FieldAllowedIPv6Addresses || k == consts.FieldAllowedPorts {
				if set, ok := v.(*schema.Set); ok {
					data[k] = set.List()
				} else {
					data[k] = v
				}
			} else {
				data[k] = v
			}
		}
	}

	log.Printf("[DEBUG] Writing sync destination data to %q", path)
	_, err := client.Logical().WriteWithContext(ctx, path, data)
	if err != nil {
		return diag.Errorf("error writing sync destination data to %q: %s", path, err)
	}
	log.Printf("[DEBUG] Wrote sync destination data to %q", path)

	if d.IsNewResource() {
		d.SetId(name)
	}

	return githubSecretsSyncDestinationRead(ctx, d, meta)
}

func githubSecretsSyncDestinationRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	readFields := []string{
		fieldRepositoryOwner,
		fieldRepositoryName,
		consts.FieldGranularity,
		consts.FieldSecretNameTemplate,
		consts.FieldAppName,
		consts.FieldInstallationID,
	}

	// Add Vault 1.18+ fields if supported
	isV118Supported := provider.IsAPISupported(meta, provider.VaultVersion118)
	if isV118Supported {
		readFields = append(readFields,
			consts.FieldSecretsLocation,
			consts.FieldEnvironmentName,
		)
	}

	// Add Vault 1.19+ fields if supported
	isV119Supported := provider.IsAPISupported(meta, provider.VaultVersion119)
	if isV119Supported {
		readFields = append(readFields,
			consts.FieldAllowedIPv4Addresses,
			consts.FieldAllowedIPv6Addresses,
			consts.FieldAllowedPorts,
			consts.FieldDisableStrictNetworking,
		)
	}

	return syncutil.SyncDestinationRead(ctx, d, meta, ghSyncType, readFields, map[string]string{
		consts.FieldGranularity: consts.FieldGranularityLevel,
	})
}

func githubSecretsSyncDestinationDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return syncutil.SyncDestinationDelete(ctx, d, meta, ghSyncType)
}
