// Copyright IBM Corp. 2016, 2026
// SPDX-License-Identifier: MPL-2.0

package pki

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/go-viper/mapstructure/v2"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-provider-vault/internal/consts"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/base"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/client"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/errutil"
	"github.com/hashicorp/terraform-provider-vault/internal/framework/model"
	"github.com/hashicorp/vault/api"
)

// exportKeyIDRegexp parses an import ID of the form "<mount>/export/<uuid>".
var exportKeyIDRegexp = regexp.MustCompile(`^(.+)/export/([^/]+)$`)

var _ resource.ResourceWithImportState = &PKIExportKeyResource{}

// NewPKIExportKeyResource is the constructor registered in provider.go.
func NewPKIExportKeyResource() resource.Resource {
	return &PKIExportKeyResource{}
}

// PKIExportKeyResource manages a wrapping key on a PKI mount.
// A wrapping key is an asymmetric keypair generated by Vault whose public half
// is shared with the source mount operator so they can encrypt a CA private key
// for migration. The private half never leaves Vault.
type PKIExportKeyResource struct {
	base.ResourceWithConfigure
}

// PKIExportKeyModel is the Terraform state model. Each field has a tfsdk tag
// that the Plugin Framework uses to read from and write to Terraform state.
type PKIExportKeyModel struct {
	base.BaseModel

	Mount         types.String `tfsdk:"mount"`
	KeyType       types.String `tfsdk:"key_type"`
	Name          types.String `tfsdk:"name"`
	ExportKeyUUID types.String `tfsdk:"export_key_uuid"`
	PublicKey     types.String `tfsdk:"public_key"`
	ExportKeyHMAC types.String `tfsdk:"export_key_hmac"`
	CreatedAt     types.String `tfsdk:"created_at"`
}

// PKIExportKeyAPIModel mirrors the JSON fields Vault returns on READ.
// mapstructure tags let model.ToAPIModel decode the raw response map in one call.
type PKIExportKeyAPIModel struct {
	ExportKeyUUID string `json:"export_key_uuid" mapstructure:"export_key_uuid"`
	Name          string `json:"name" mapstructure:"name"`
	KeyType       string `json:"key_type" mapstructure:"key_type"`
	PublicKey     string `json:"public_key" mapstructure:"public_key"`
	ExportKeyHMAC string `json:"export_key_hmac" mapstructure:"export_key_hmac"`
	CreatedAt     string `json:"created_at" mapstructure:"created_at"`
}

// PKIExportKeyWriteAPIModel is the request body for POST /pki/export.
type PKIExportKeyWriteAPIModel struct {
	KeyType string `mapstructure:"key_type"`
	Name    string `mapstructure:"name,omitempty"`
}

func (r *PKIExportKeyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pki_secret_backend_export_key"
}

func (r *PKIExportKeyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a BYOK wrapping key on a PKI secrets engine mount. " +
			"Vault generates an asymmetric keypair; the public key is shared with the source " +
			"mount operator for CA key encryption. The private key never leaves Vault.",
		Attributes: map[string]schema.Attribute{
			consts.FieldMount: schema.StringAttribute{
				Description: "Path of the PKI secrets engine mount.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					// There is no move API. Changing the mount requires destroy + recreate.
					stringplanmodifier.RequiresReplace(),
				},
			},
			"key_type": schema.StringAttribute{
				Description: `Wrapping key algorithm. Supported values: "rsa-2048", "rsa-3072", "rsa-4096", "rsa-8192", "ec-p256", "ec-p384", "ec-p521", "ml-kem-768", "ml-kem-1024".`,
				Required:    true,
				PlanModifiers: []planmodifier.String{
					// Vault generates the keypair on creation; the algorithm cannot be changed.
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Optional human-readable label for this export key.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					// Vault has no update endpoint — name is set at creation time only.
					stringplanmodifier.RequiresReplace(),
				},
			},
			"export_key_uuid": schema.StringAttribute{
				Description: "UUID assigned by Vault to this export key.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"public_key": schema.StringAttribute{
				Description: "PKIX PEM-encoded public key. Pass this to the source mount operator to encrypt the CA private key.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"export_key_hmac": schema.StringAttribute{
				Description: `SHA-256 HMAC fingerprint of the public key (format "sha256:<hex>"). Pass this alongside wrapped_key to the import endpoint.`,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created_at": schema.StringAttribute{
				Description: "RFC3339 timestamp of when this export key was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}

	// MustAddBaseSchema injects the "namespace" field required by every Plugin
	// Framework resource in this provider for Vault Enterprise namespace routing.
	base.MustAddBaseSchema(&resp.Schema)
}

// Create calls POST /:mount/export. Vault generates the keypair, returns the
// UUID, public key, and HMAC. We follow up with a Read to populate fields the
// create response omits (created_at, name).
func (r *PKIExportKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data PKIExportKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	vaultClient, err := client.GetClient(ctx, r.Meta(), data.Namespace.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(errutil.ClientConfigureErr(err))
		return
	}

	requestBody, diags := r.buildWriteRequest(&data)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	vaultResp, err := vaultClient.Logical().WriteWithContext(ctx, r.exportPath(data.Mount.ValueString()), requestBody)
	if err != nil {
		resp.Diagnostics.AddError(errutil.VaultCreateErr(err))
		return
	}
	if vaultResp == nil {
		resp.Diagnostics.AddError(errutil.VaultReadResponseNil())
		return
	}

	uuid, ok := vaultResp.Data["export_key_uuid"].(string)
	if !ok || uuid == "" {
		resp.Diagnostics.AddError("Unexpected Vault response", "export_key_uuid missing from create response")
		return
	}
	data.ExportKeyUUID = types.StringValue(uuid)

	if diags := r.readIntoModel(ctx, vaultClient, &data); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Read calls GET /:mount/export/:uuid and refreshes all computed fields.
// If Vault returns nil the key was deleted out of band; we remove it from state.
func (r *PKIExportKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data PKIExportKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	vaultClient, err := client.GetClient(ctx, r.Meta(), data.Namespace.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(errutil.ClientConfigureErr(err))
		return
	}

	diags := r.readIntoModel(ctx, vaultClient, &data)
	if diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Update is required by the resource.Resource interface but will never be
// called — every user-settable field is RequiresReplace, so Terraform destroys
// and recreates rather than updating.
func (r *PKIExportKeyResource) Update(_ context.Context, _ resource.UpdateRequest, _ *resource.UpdateResponse) {
}

// Delete calls DELETE /:mount/export/:uuid.
func (r *PKIExportKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data PKIExportKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	vaultClient, err := client.GetClient(ctx, r.Meta(), data.Namespace.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(errutil.ClientConfigureErr(err))
		return
	}

	_, err = vaultClient.Logical().DeleteWithContext(ctx, r.exportKeyPath(data.Mount.ValueString(), data.ExportKeyUUID.ValueString()))
	if err != nil {
		resp.Diagnostics.AddError(errutil.VaultDeleteErr(err))
	}
}

// ImportState allows an export key that already exists in Vault to be brought under
// Terraform management without destroying it. The import ID must be <mount>/export/<uuid>.
func (r *PKIExportKeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	mount, uuid, err := parseExportKeyID(req.ID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid import identifier",
			fmt.Sprintf("Expected <mount>/export/<uuid>, got %q: %s", req.ID, err),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(consts.FieldMount), mount)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("export_key_uuid"), uuid)...)

	ns := os.Getenv(consts.EnvVarVaultNamespaceImport)
	if ns != "" {
		tflog.Info(ctx, fmt.Sprintf("Environment variable %s set, importing namespace into state", consts.EnvVarVaultNamespaceImport))
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(consts.FieldNamespace), ns)...)
	}
}

// readIntoModel performs GET /:mount/export/:uuid and populates all fields in data.
func (r *PKIExportKeyResource) readIntoModel(ctx context.Context, vaultClient *api.Client, data *PKIExportKeyModel) diag.Diagnostics {
	vaultResp, err := vaultClient.Logical().ReadWithContext(ctx, r.exportKeyPath(data.Mount.ValueString(), data.ExportKeyUUID.ValueString()))
	if err != nil {
		return diag.Diagnostics{diag.NewErrorDiagnostic(errutil.VaultReadErr(err))}
	}
	if vaultResp == nil {
		return diag.Diagnostics{diag.NewErrorDiagnostic(errutil.VaultReadResponseNil())}
	}

	var apiModel PKIExportKeyAPIModel
	if err := model.ToAPIModel(vaultResp.Data, &apiModel); err != nil {
		return diag.Diagnostics{diag.NewErrorDiagnostic("Unable to decode Vault response", err.Error())}
	}

	data.ExportKeyUUID = types.StringValue(apiModel.ExportKeyUUID)
	data.KeyType = types.StringValue(apiModel.KeyType)
	data.PublicKey = types.StringValue(apiModel.PublicKey)
	data.ExportKeyHMAC = types.StringValue(apiModel.ExportKeyHMAC)
	data.CreatedAt = types.StringValue(apiModel.CreatedAt)

	if apiModel.Name != "" {
		data.Name = types.StringValue(apiModel.Name)
	} else {
		data.Name = types.StringNull()
	}

	return nil
}

func (r *PKIExportKeyResource) buildWriteRequest(data *PKIExportKeyModel) (map[string]any, diag.Diagnostics) {
	apiModel := PKIExportKeyWriteAPIModel{
		KeyType: data.KeyType.ValueString(),
		Name:    data.Name.ValueString(),
	}

	var out map[string]any
	if err := mapstructure.Decode(apiModel, &out); err != nil {
		return nil, diag.Diagnostics{
			diag.NewErrorDiagnostic("Failed to encode export key request", err.Error()),
		}
	}

	return out, nil
}

func (r *PKIExportKeyResource) exportPath(mount string) string {
	return fmt.Sprintf("%s/export", mount)
}

func (r *PKIExportKeyResource) exportKeyPath(mount, uuid string) string {
	return fmt.Sprintf("%s/export/%s", mount, uuid)
}

func parseExportKeyID(id string) (mount, uuid string, err error) {
	id = strings.Trim(id, "/")
	matches := exportKeyIDRegexp.FindStringSubmatch(id)
	if len(matches) != 3 {
		return "", "", fmt.Errorf("must be of the form <mount>/export/<uuid>")
	}
	return matches[1], matches[2], nil
}
