name: build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  PKG_NAME: "terraform-provider-vault"

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - id: go-version
        run: echo "version=$(cat .go-version)" >> "$GITHUB_OUTPUT"

  set-product-version:
    name: "Parse version file"
    runs-on: ubuntu-latest
    outputs:
      product-version: ${{ steps.set-product-version.outputs.product-version }}
      product-base-version: ${{ steps.set-product-version.outputs.base-product-version }}
      product-prerelease-version: ${{ steps.set-product-version.outputs.prerelease-product-version }}
      product-minor-version: ${{ steps.set-product-version.outputs.minor-product-version }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set variables
        id: set-product-version
        uses: hashicorp/actions-set-product-version@v2

  generate-metadata-file:
    needs: set-product-version
    runs-on: ubuntu-latest
    outputs:
      filepath: ${{ steps.generate-metadata-file.outputs.filepath }}
    steps:
      - name: "Checkout directory"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Generate metadata file
        id: generate-metadata-file
        uses: hashicorp/actions-generate-metadata@v1
        with:
          version: ${{ needs.set-product-version.outputs.product-version }}
          product: ${{ env.PKG_NAME }}
          repositoryOwner: "hashicorp"
          repository: "terraform-provider-vault"
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: metadata.json
          path: ${{ steps.generate-metadata-file.outputs.filepath }}

  build-pre:
    needs: [go-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: '.go-version'
          cache: false
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '1.12.*'
          terraform_wrapper: false

      - name: Cache go build
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Run unit tests
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          make test

  build:
    needs:
      - build-pre
      - go-version
      - set-product-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        goos: [ freebsd, windows, linux, darwin ]
        goarch: [ "386", "amd64", "arm", "arm64" ]
        exclude:
          - goos: freebsd
            goarch: arm64
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: arm
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm

    name: Go ${{ needs.go-version.outputs.version }} ${{ matrix.goos }} ${{ matrix.goarch }} build
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: hashicorp/actions-go-build@v1
        env:
          CGO_ENABLED: 0
          BASE_VERSION: ${{ needs.set-product-version.outputs.product-base-version }}
          PRERELEASE_VERSION: ${{ needs.set-product-version.outputs.product-prerelease-version}}
          METADATA_VERSION: ${{ env.METADATA }}
        with:
          bin_name: "${{ env.PKG_NAME }}_v${{ needs.set-product-version.outputs.product-version }}_x5"
          product_name: ${{ env.PKG_NAME }}
          product_version: ${{ needs.set-product-version.outputs.product-version }}
          go_version: ${{ needs.go-version.outputs.version }}
          os: ${{ matrix.goos }}
          arch: ${{ matrix.goarch }}
          reproducible: report
          instructions: |
            go build \
              -o "$BIN_PATH" \
              -trimpath \
              -buildvcs=false \
              -ldflags "-s -w"
            cp LICENSE "$TARGET_DIR/LICENSE.txt"

  acceptance:
    name: vault_image:${{ matrix.image }} tf_version:${{ matrix.terraform_version }}
    needs: [go-version, build-pre]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "vault-enterprise:1.19.16-ent"
          - "vault-enterprise:1.19.17-ent"
          - "vault-enterprise:1.20.10-ent"
          - "vault-enterprise:1.20.11-ent"
          - "vault-enterprise:1.21.5-ent"
          - "vault-enterprise:1.21.6-ent"
          - "vault-enterprise:2.0.0-ent"
          - "vault-enterprise:2.0.1-ent"
          - "vault:latest"
        terraform_version:
          - "latest"
          - "1.12.2"
          - "1.11.4"

    services:
      mysql:
        image: docker.mirror.hashicorp.services/mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306:3306

      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        ports:
          - 1433:1433

      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: mongodb
          MONGO_INITDB_DATABASE: admin
        ports:
          - 27017:27017

      postgres:
        image: docker.mirror.hashicorp.services/postgres:latest
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: database
        ports:
          - 5432:5432

      couchbase:
        image: docker.io/couchbase/server-sandbox:7.1.1
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 11207:11207
          - 11210:11210
          - 18091:18091
          - 18092:18092
          - 18093:18093
          - 18094:18094
        options: >-
          --health-cmd "curl -f http://Administrator:password@127.0.0.1:8091/sampleBuckets"
          --health-interval 1s
          --health-timeout 5s
          --health-retries 60

      consul:
        image: docker.mirror.hashicorp.services/hashicorp/consul:latest
        env:
          CONSUL_LOCAL_CONFIG: "{\"acl\":{\"enabled\":true}}"
        ports:
          - 8500:8500
          - 8600:8600
        options: >-
          --health-cmd "curl -f 'http://127.0.0.1:8500/v1/health/node/server-1'"
          --health-interval 1s
          --health-timeout 5s
          --health-retries 5

      openldap:
        image: osixia/openldap:1.5.0
        ports:
          - 10389:389
        options: >-
          --health-cmd "sleep 10"
          --health-interval 1s
          --health-timeout 30s
          --health-retries 30

      pebble:
        image: ghcr.io/letsencrypt/pebble:2.8.0
        options: --add-host=host.docker.internal:host-gateway
        ports:
          - 14000:14000

    steps:
      - name: Update apt cache
        run: |
          sudo apt-get update
        timeout-minutes: 2

      - name: install ldap utils
        run: |
          sudo apt-get install -y ldap-utils

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: '.go-version'
          cache: false

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ matrix.terraform_version }}
          terraform_wrapper: false

      - name: Check Terraform CLI version
        run: terraform --version

      - name: Start Vault container with IPC_LOCK
        run: |
          docker run -d \
            --name vault \
            --cap-add=IPC_LOCK \
            -e VAULT_DEV_ROOT_TOKEN_ID=root \
            -e VAULT_LOCAL_CONFIG='{"plugin_directory": "/vault/plugins", "disable_mlock": true}' \
            -p 8200:8200 \
            -v ${{ github.workspace }}:/vault/plugins \
            hashicorp/${{ matrix.image }} \
            server -dev

          echo "Waiting for Vault..."

          for i in {1..30}; do
            if curl -s http://localhost:8200/v1/sys/health > /dev/null; then
              echo "Vault is up"
              break
            fi
            sleep 2
          done

      - name: Download external plugin
        id: plugin
        env:
          PLUGIN: "vault-plugin-auth-jwt"
          VERSION: "0.17.0"
        run: |
          ZIP="${PLUGIN}_${VERSION}_linux_amd64.zip"
          SHA256SUMS="${PLUGIN}_${VERSION}_SHA256SUMS"
          curl -sO "https://releases.hashicorp.com/${PLUGIN}/${VERSION}/{${ZIP},${SHA256SUMS}}"
          shasum -a 256 -c "${PLUGIN}_${VERSION}_SHA256SUMS" --ignore-missing
          unzip "${ZIP}"
          rm "${ZIP}" "${SHA256SUMS}"
          echo "command=${PLUGIN}" >> "${GITHUB_OUTPUT}"

      - name: Download OS secrets plugin
        id: os_plugin
        env:
          PLUGIN: "vault-plugin-secrets-os"
          VERSION: "0.1.0+ent"
        run: |
          ZIP="${PLUGIN}_${VERSION}_linux_amd64.zip"
          DIR="${PLUGIN}_${VERSION}_linux_amd64"

          curl -fsSL -O "https://releases.hashicorp.com/${PLUGIN}/${VERSION}/${ZIP}"

          mkdir -p "${DIR}"
          unzip "${ZIP}" -d "${DIR}"
          rm "${ZIP}"
          chmod -R a+r "${DIR}/metadata.json.sig"

          echo "downloaded=true" >> "${GITHUB_OUTPUT}"

      - name: Download external Enterprise plugin
        id: plugin_enterprise
        env:
          TYPE: "database"
          PLUGIN: "vault-plugin-database-oracle"
          VERSION: "0.13.0+ent"
        run: |
          ZIP="${PLUGIN}_${VERSION}_linux_amd64.zip"
          ZIP_DIR="${PLUGIN}_${VERSION}_linux_amd64"
          SHA256SUMS="${PLUGIN}_${VERSION}_SHA256SUMS"

          curl -sO "https://releases.hashicorp.com/${PLUGIN}/${VERSION}/{${ZIP},${SHA256SUMS}}"

          shasum -a 256 -c "${PLUGIN}_${VERSION}_SHA256SUMS" --ignore-missing

          unzip "${ZIP}" -d "${ZIP_DIR}"

          rm "${ZIP}" "${SHA256SUMS}"

          chmod a+r "${ZIP_DIR}/metadata.json.sig"

          {
            echo "type=${TYPE}"
            echo "name=${PLUGIN}"
            echo "version=${VERSION}"
          } >> "${GITHUB_OUTPUT}"

      - name: Cache go build
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Acceptance Tests
        env:
          VAULT_TOKEN: "root"
          VAULT_ADDR: "http://localhost:8200"
          RUNS_IN_CONTAINER: "false"
          MYSQL_URL: "root:mysql@tcp(mysql:3306)/"
          MYSQL_CONNECTION_URL: "{{username}}:{{password}}@tcp(mysql:3306)/"
          MYSQL_CONNECTION_USERNAME: "root"
          MYSQL_CONNECTION_PASSWORD: "mysql"
          MONGODB_URL: "mongodb://root:mongodb@mongo:27017/admin?ssl=false"
          MSSQL_URL: "sqlserver://sa:${{ secrets.MSSQL_SA_PASSWORD }}@mssql:1433"
          POSTGRES_URL: "postgres://postgres:secret@postgres:5432/database?sslmode=disable"
          POSTGRES_URL_TEST: "postgres://postgres:secret@localhost:5432/database?sslmode=disable"
          POSTGRES_URL_ROOTLESS: "postgres://{{username}}:{{password}}@postgres:5432/database?sslmode=disable"
          COUCHBASE_HOST: couchbase
          COUCHBASE_USERNAME: Administrator
          COUCHBASE_PASSWORD: password
          CONSUL_HTTP_ADDR: "consul:8500"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LDAP_BINDDN: "cn=admin,dc=example,dc=org"
          LDAP_BINDPASS: "admin"
          LDAP_HOST_URL: "ldap://0.0.0.0:10389"
          LDAP_URL: "ldap://openldap:389"
          VAULT_PLUGIN_COMMAND: ${{ steps.plugin.outputs.command }}
          VAULT_PLUGIN_ENT_TYPE: ${{ steps.plugin_enterprise.outputs.type }}
          VAULT_PLUGIN_ENT_NAME: ${{ steps.plugin_enterprise.outputs.name }}
          VAULT_PLUGIN_ENT_VERSION: ${{ steps.plugin_enterprise.outputs.version }}
        run: |
          if [[ ${{ matrix.image }} =~ "-ent" ]]; then
            target="testacc-ent"
          else
            target="testacc"
          fi

          if [ -n "${{ env.LDAP_HOST_URL }}" ]; then
            cat testdata/openldap/ldif/*.ldif | ldapadd -x -H ${{ env.LDAP_HOST_URL }} -D "${{ env.LDAP_BINDDN }}" -w "${{ env.LDAP_BINDPASS }}"
          fi

          make $target TESTARGS='-test.v -tags=testonly' SKIP_MSSQL_MULTI_CI=true SKIP_RAFT_TESTS=true SKIP_VAULT_NEXT_TESTS=true TF_ACC_K8S_SKIP_IN_CLUSTER=true

      - name: "Generate Vault API Path Coverage Report"
        run: |
          go run cmd/coverage/main.go -openapi-doc=./testdata/openapi.json

      - name: Debug Vault logs
        if: failure()
        run: docker logs vault

  upload-terraform-registry-manifest-artifact:
    needs:
      - set-product-version
      - build
      - acceptance
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout directory"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          path: ${{ env.PKG_NAME }}

      - name: "Copy manifest from checkout directory to a file with the desired name"
        id: terraform-registry-manifest
        run: |
          name="${{ env.PKG_NAME }}"
          version="${{ needs.set-product-version.outputs.product-version }}"

          source="${name}/terraform-registry-manifest.json"
          destination="${name}_${version}_manifest.json"

          cp "$source" "$destination"

          echo "filename=$destination" >> "${GITHUB_OUTPUT}"

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: terraform-registry-manifest.json
          path: ${{ steps.terraform-registry-manifest.outputs.filename }}
          if-no-files-found: error

  build-done:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - acceptance
      - upload-terraform-registry-manifest-artifact
      - generate-metadata-file

    steps:
      - name: cancelled
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: exit 2

      - name: passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1